/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ExpenseScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoadingOverlay`; params?: Router.UnknownInputParams; } | { pathname: `/useLoadingState`; params?: Router.UnknownInputParams; } | { pathname: `/withLoading`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SpendPlaner` | `/SpendPlaner`; params?: Router.UnknownInputParams; } | { pathname: `/destinations/categories`; params?: Router.UnknownInputParams; } | { pathname: `/destinations/exploreMap`; params?: Router.UnknownInputParams; } | { pathname: `/blog/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/destinations/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ExpenseScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoadingOverlay`; params?: Router.UnknownOutputParams; } | { pathname: `/useLoadingState`; params?: Router.UnknownOutputParams; } | { pathname: `/withLoading`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SpendPlaner` | `/SpendPlaner`; params?: Router.UnknownOutputParams; } | { pathname: `/destinations/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/destinations/exploreMap`; params?: Router.UnknownOutputParams; } | { pathname: `/blog/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/destinations/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/ExpenseScreen${`?${string}` | `#${string}` | ''}` | `/LoadingOverlay${`?${string}` | `#${string}` | ''}` | `/useLoadingState${`?${string}` | `#${string}` | ''}` | `/withLoading${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chatbot${`?${string}` | `#${string}` | ''}` | `/chatbot${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/itinerary${`?${string}` | `#${string}` | ''}` | `/itinerary${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/saved${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SpendPlaner${`?${string}` | `#${string}` | ''}` | `/SpendPlaner${`?${string}` | `#${string}` | ''}` | `/destinations/categories${`?${string}` | `#${string}` | ''}` | `/destinations/exploreMap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ExpenseScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoadingOverlay`; params?: Router.UnknownInputParams; } | { pathname: `/useLoadingState`; params?: Router.UnknownInputParams; } | { pathname: `/withLoading`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SpendPlaner` | `/SpendPlaner`; params?: Router.UnknownInputParams; } | { pathname: `/destinations/categories`; params?: Router.UnknownInputParams; } | { pathname: `/destinations/exploreMap`; params?: Router.UnknownInputParams; } | `/blog/${Router.SingleRoutePart<T>}` | `/destinations/${Router.SingleRoutePart<T>}` | { pathname: `/blog/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/destinations/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
